"""Source Registry – Seed der 26 freigegebenen Quellen (Welle 1–4).

Alle Zugriffswege wurden am 25.08.2026 live verifiziert (HTTP 200, mit dem
Scraper-User-Agent). Verbandsquellen (LICENSED) sind bewusst nicht enthalten.
FATF ist komplett hinter Cloudflare-Bot-Schutz (403 auf allen Pfaden) und
wird nicht umgangen – daher keine FATF-Quelle.
"""

SOURCES = [
    # ---------------- Welle 1: Core Legal ----------------
    {
        "source_id": "eurlex",
        "name": "EUR-Lex / CELLAR",
        "authority": "Amt für Veröffentlichungen der EU",
        "jurisdiction": "EU",
        "base_url": "https://eur-lex.europa.eu/",
        "discovery_url": "https://publications.europa.eu/webapi/rdf/sparql",
        "discovery_type": "API",
        "access_class": "PUBLIC",
        "document_types": ["REGULATION", "DIRECTIVE", "DELEGATED_REGULATION", "IMPLEMENTING_REGULATION"],
        "poll_interval_minutes": 720,
        "adapter": "eurlex",
        "enabled": 1,
    },
    {
        "source_id": "gii",
        "name": "Gesetze im Internet",
        "authority": "Bundesministerium der Justiz",
        "jurisdiction": "DE",
        "base_url": "https://www.gesetze-im-internet.de/",
        "discovery_url": "https://www.gesetze-im-internet.de/gii-toc.xml",
        "discovery_type": "XML",
        "access_class": "PUBLIC",
        "document_types": ["LAW"],
        "poll_interval_minutes": 1440,
        "adapter": "gii",
        "enabled": 1,
    },
    {
        "source_id": "dip",
        "name": "DIP Bundestag/Bundesrat",
        "authority": "Deutscher Bundestag",
        "jurisdiction": "DE",
        "base_url": "https://dip.bundestag.de/",
        "discovery_url": "https://search.dip.bundestag.de/api/v1/",
        "discovery_type": "API",
        "access_class": "PUBLIC",  # API-Key frei publiziert, via env DIP_API_KEY
        "document_types": ["LEGISLATIVE_PROPOSAL", "PARLIAMENTARY_DOCUMENT"],
        "poll_interval_minutes": 720,
        "adapter": "dip",
        "enabled": 1,
    },
    {
        "source_id": "bgbl",
        "name": "Bundesgesetzblatt (recht.bund.de)",
        "authority": "Bundesamt für Justiz",
        "jurisdiction": "DE",
        "base_url": "https://www.recht.bund.de/",
        "discovery_url": "https://www.recht.bund.de/rss/feeds/rss_bgbl-1.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["LAW"],
        "poll_interval_minutes": 720,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "rii",
        "name": "Rechtsprechung im Internet",
        "authority": "Bundesgerichte",
        "jurisdiction": "DE",
        "base_url": "https://www.rechtsprechung-im-internet.de/",
        "discovery_url": "https://www.rechtsprechung-im-internet.de/rii-toc.xml",
        "discovery_type": "XML",
        "access_class": "PUBLIC",
        "document_types": ["COURT_DECISION"],
        "poll_interval_minutes": 1440,
        "adapter": "rii",
        "enabled": 1,
    },
    # ---------------- Welle 2: Aufsichtsbehörden ----------------
    {
        "source_id": "amla",
        "name": "AMLA",
        "authority": "AMLA",
        "jurisdiction": "EU",
        "base_url": "https://www.amla.europa.eu/",
        "discovery_url": "https://www.amla.europa.eu/sitemap.xml",
        "discovery_type": "SITEMAP",
        "access_class": "PUBLIC",
        "document_types": ["RTS", "ITS", "GUIDELINE", "CONSULTATION", "FINAL_REPORT", "OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "amla",
        "enabled": 1,
    },
    {
        "source_id": "bafin",
        "name": "BaFin",
        "authority": "BaFin",
        "jurisdiction": "DE",
        "base_url": "https://www.bafin.de/",
        "discovery_url": "https://www.bafin.de/DE/service/rss/_function/rssnewsfeed.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["CIRCULAR", "CONSULTATION", "ADMINISTRATIVE_PRACTICE", "GENERAL_DECISION", "OTHER"],
        "poll_interval_minutes": 360,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "eba",
        "name": "EBA",
        "authority": "EBA",
        "jurisdiction": "EU",
        "base_url": "https://www.eba.europa.eu/",
        "discovery_url": "https://www.eba.europa.eu/rss.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["GUIDELINE", "RTS", "ITS", "Q_AND_A", "CONSULTATION", "OTHER"],
        "poll_interval_minutes": 360,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "esma",
        "name": "ESMA",
        "authority": "ESMA",
        "jurisdiction": "EU",
        "base_url": "https://www.esma.europa.eu/",
        "discovery_url": "https://www.esma.europa.eu/rss.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["GUIDELINE", "RTS", "ITS", "Q_AND_A", "CONSULTATION", "OTHER"],
        "poll_interval_minutes": 360,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "ecb_ssm",
        "name": "EZB Bankenaufsicht (SSM)",
        "authority": "EZB",
        "jurisdiction": "EU",
        "base_url": "https://www.bankingsupervision.europa.eu/",
        "discovery_url": "https://www.bankingsupervision.europa.eu/rss/press.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["SUPERVISORY_STATEMENT", "CONSULTATION", "OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "bundesbank",
        "name": "Deutsche Bundesbank",
        "authority": "Bundesbank",
        "jurisdiction": "DE",
        "base_url": "https://www.bundesbank.de/",
        "discovery_url": "https://www.bundesbank.de/service/rss/de/633302/feed.rss",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["CIRCULAR", "OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "rss",
        "enabled": 1,
    },
    # ---------------- Welle 3: EU-Ausbau + Frühwarnsignale ----------------
    {
        "source_id": "eiopa",
        "name": "EIOPA",
        "authority": "EIOPA",
        "jurisdiction": "EU",
        "base_url": "https://www.eiopa.europa.eu/",
        "discovery_url": "https://www.eiopa.europa.eu/sitemap.xml",
        "discovery_type": "SITEMAP",
        "access_class": "PUBLIC",
        "document_types": ["GUIDELINE", "RTS", "ITS", "CONSULTATION", "OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "eiopa",
        "enabled": 1,
    },
    {
        "source_id": "srb",
        "name": "Single Resolution Board",
        "authority": "SRB",
        "jurisdiction": "EU",
        "base_url": "https://www.srb.europa.eu/",
        "discovery_url": "https://www.srb.europa.eu/en/rss",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["CONSULTATION", "SUPERVISORY_STATEMENT", "OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "curia",
        "name": "EuGH (curia, Pressemitteilungen)",
        "authority": "EuGH",
        "jurisdiction": "EU",
        "base_url": "https://curia.europa.eu/",
        "discovery_url": "https://curia.europa.eu/jcms/jcms/Jo2_7052/en/",
        "discovery_type": "HTML",
        "access_class": "PUBLIC",
        "document_types": ["COURT_DECISION"],
        "poll_interval_minutes": 1440,
        "adapter": "curia",
        "enabled": 1,
    },
    {
        "source_id": "bmf",
        "name": "Bundesministerium der Finanzen",
        "authority": "BMF",
        "jurisdiction": "DE",
        "base_url": "https://www.bundesfinanzministerium.de/",
        "discovery_url": "https://www.bundesfinanzministerium.de/sitemap.xml",
        "discovery_type": "SITEMAP",
        "access_class": "PUBLIC",
        "document_types": ["LEGISLATIVE_PROPOSAL", "LAW"],
        "poll_interval_minutes": 720,
        "adapter": "bmf",
        "enabled": 1,
    },
    {
        "source_id": "hys",
        "name": "EU-Kommission „Have Your Say\"",
        "authority": "Europäische Kommission",
        "jurisdiction": "EU",
        "base_url": "https://ec.europa.eu/info/law/better-regulation/have-your-say/",
        "discovery_url": "https://ec.europa.eu/info/law/better-regulation/brpapi/searchInitiatives",
        "discovery_type": "API",
        "access_class": "PUBLIC",
        "document_types": ["CONSULTATION", "LEGISLATIVE_PROPOSAL"],
        "poll_interval_minutes": 720,
        "adapter": "hys",
        "enabled": 1,
    },
    # ---------------- Welle 4: Q&A/Register, Datenschutz/Cyber, GwG, International ----------------
    {
        "source_id": "eba_qna",
        "name": "EBA Single Rulebook Q&A",
        "authority": "EBA",
        "jurisdiction": "EU",
        "base_url": "https://www.eba.europa.eu/single-rule-book-qa",
        "discovery_url": "https://www.eba.europa.eu/single-rule-book-qa/all?order=field_answer_publication_date&sort=desc",
        "discovery_type": "HTML",
        "access_class": "PUBLIC",
        "document_types": ["Q_AND_A"],
        "poll_interval_minutes": 720,
        "adapter": "ebaqna",
        "enabled": 1,
    },
    {
        "source_id": "esma_library",
        "name": "ESMA Library (Register/Dokumente)",
        "authority": "ESMA",
        "jurisdiction": "EU",
        "base_url": "https://www.esma.europa.eu/databases-library/esma-library",
        "discovery_url": "https://www.esma.europa.eu/databases-library/esma-library?search_api_fulltext=&items_per_page=50&order=created&sort=desc",
        "discovery_type": "HTML",
        "access_class": "PUBLIC",
        "document_types": ["GUIDELINE", "RTS", "ITS", "Q_AND_A", "CONSULTATION", "FINAL_REPORT", "OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "esmalib",
        "enabled": 1,
    },
    {
        "source_id": "bsi",
        "name": "BSI (Presse-/Kurzmitteilungen)",
        "authority": "BSI",
        "jurisdiction": "DE",
        "base_url": "https://www.bsi.bund.de/",
        "discovery_url": "https://www.bsi.bund.de/SiteGlobals/Functions/RSSFeed/RSSNewsfeed/RSSNewsfeed_Presse_Veranstaltungen.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "edpb",
        "name": "Europäischer Datenschutzausschuss (EDPB)",
        "authority": "EDPB",
        "jurisdiction": "EU",
        "base_url": "https://www.edpb.europa.eu/",
        "discovery_url": "https://www.edpb.europa.eu/feed/news_en",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["GUIDELINE", "CONSULTATION", "OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "bfdi",
        "name": "BfDI",
        "authority": "BfDI",
        "jurisdiction": "DE",
        "base_url": "https://www.bfdi.bund.de/",
        "discovery_url": "https://www.bfdi.bund.de/SiteGlobals/Functions/RSSFeed/Allgemein/rssnewsfeed.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["OTHER"],
        "poll_interval_minutes": 1440,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "fiu",
        "name": "FIU Deutschland (Fachmeldungen)",
        "authority": "FIU",
        "jurisdiction": "DE",
        "base_url": "https://www.zoll.de/DE/FIU/fiu_node.html",
        "discovery_url": "https://www.zoll.de/SiteGlobals/Functions/RSSFeed/DE/RSSNewsfeed/RSSFachmeldungenFIU.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["OTHER"],
        "poll_interval_minutes": 1440,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "esrb",
        "name": "European Systemic Risk Board",
        "authority": "ESRB",
        "jurisdiction": "EU",
        "base_url": "https://www.esrb.europa.eu/",
        "discovery_url": "https://www.esrb.europa.eu/rss/press.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["OTHER"],
        "poll_interval_minutes": 1440,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "bis",
        "name": "Basler Ausschuss (BIS/BCBS)",
        "authority": "BCBS",
        "jurisdiction": "INT",
        "base_url": "https://www.bis.org/bcbs/",
        "discovery_url": "https://www.bis.org/doclist/bcbspubls.rss",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["FINAL_REPORT", "CONSULTATION", "OTHER"],
        "poll_interval_minutes": 1440,
        "adapter": "rss",
        "enabled": 0,  # RSS-Feed seit 09/2026 dauerhaft 404 – Quelle deaktiviert
    },
    {
        "source_id": "fsb",
        "name": "Financial Stability Board",
        "authority": "FSB",
        "jurisdiction": "INT",
        "base_url": "https://www.fsb.org/",
        "discovery_url": "https://www.fsb.org/feed/",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["FINAL_REPORT", "CONSULTATION", "OTHER"],
        "poll_interval_minutes": 1440,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "iosco",
        "name": "IOSCO (Public Reports)",
        "authority": "IOSCO",
        "jurisdiction": "INT",
        "base_url": "https://www.iosco.org/",
        "discovery_url": "https://www.iosco.org/publications/?subsection=public_reports",
        "discovery_type": "HTML",
        "access_class": "PUBLIC",
        "document_types": ["FINAL_REPORT", "CONSULTATION", "OTHER"],
        "poll_interval_minutes": 1440,
        "adapter": "iosco",
        "enabled": 1,
    },
    # ---------------- Welle 5: AI Act (30.08.2026) ----------------
    {
        "source_id": "ec_ai",
        "name": "EU-Kommission / AI Office (digital-strategy)",
        "authority": "Europäische Kommission (AI Office)",
        "jurisdiction": "EU",
        "base_url": "https://digital-strategy.ec.europa.eu/",
        # topic=119 = Taxonomie-Term "Artificial intelligence" (via Drupal-
        # Autocomplete verifiziert); der Site-RSS (/en/rss.xml) ist
        # ungefiltert, nur 10 Items und mischt Events/Tender aller Themen.
        "discovery_url": "https://digital-strategy.ec.europa.eu/en/news?topic=119",
        "discovery_type": "HTML",
        "access_class": "PUBLIC",
        "document_types": ["GUIDELINE", "CONSULTATION", "FINAL_REPORT", "OTHER"],
        "poll_interval_minutes": 360,
        "adapter": "dsnews",
        "enabled": 1,
    },
    # ---------------- Welle 6: Luxemburg, DG FISMA, EZB (03.09.2026) ----------------
    {
        "source_id": "cssf",
        "name": "CSSF Luxemburg",
        "authority": "CSSF",
        "jurisdiction": "LU",
        "base_url": "https://www.cssf.lu/",
        # Typisierte RSS-Feeds (content_type=…), alle am 03.09.2026 live
        # verifiziert (HTTP 200, pubDate vorhanden). Der ungefilterte
        # Publikationsfeed enthält Listen/Statistiken und wird nicht genutzt.
        "discovery_url": "https://www.cssf.lu/en/feed/publications?content_type=circular-cssf",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["CIRCULAR", "REGULATION", "CONSULTATION", "Q_AND_A", "LAW", "OTHER"],
        "poll_interval_minutes": 360,
        "adapter": "rss",
        "enabled": 1,
    },
    {
        "source_id": "ec_fisma",
        "name": "EU-Kommission / GD FISMA (Finance News)",
        "authority": "Europäische Kommission (GD FISMA)",
        "jurisdiction": "EU",
        "base_url": "https://finance.ec.europa.eu/",
        # Kein RSS auf finance.ec.europa.eu; die News-Liste (ECL-Markup wie
        # digital-strategy) liefert Typ, Datum, Titel und Teaser je Eintrag.
        "discovery_url": "https://finance.ec.europa.eu/finance-news_en",
        "discovery_type": "HTML",
        "access_class": "PUBLIC",
        "document_types": ["LEGISLATIVE_PROPOSAL", "CONSULTATION", "FINAL_REPORT", "OTHER"],
        "poll_interval_minutes": 360,
        "adapter": "ecfinance",
        "enabled": 1,
    },
    {
        "source_id": "ecb",
        "name": "EZB (Pressemitteilungen)",
        "authority": "EZB",
        "jurisdiction": "EU",
        "base_url": "https://www.ecb.europa.eu/",
        # Digitaler Euro, IReF, Zahlungsverkehrsinfrastruktur (TARGET) –
        # ergänzt den SSM-Feed der Bankenaufsicht; Reden filtert NOISE.
        "discovery_url": "https://www.ecb.europa.eu/rss/press.xml",
        "discovery_type": "RSS",
        "access_class": "PUBLIC",
        "document_types": ["OTHER"],
        "poll_interval_minutes": 720,
        "adapter": "rss",
        "enabled": 1,
    },
]

# Zusätzliche Feeds pro RSS-Quelle (werden alle abgefragt); Mapping auf Dokumenttyp.
RSS_FEEDS = {
    "bgbl": [
        ("https://www.recht.bund.de/rss/feeds/rss_bgbl-1.xml", "LAW", "de"),
        ("https://www.recht.bund.de/rss/feeds/rss_bgbl-2.xml", "LAW", "de"),
    ],
    "bafin": [
        ("https://www.bafin.de/DE/service/rss/_function/RSS_Rundschreiben.xml", "CIRCULAR", "de"),
        ("https://www.bafin.de/DE/service/rss/_function/RSS_Aufsicht.xml", "ADMINISTRATIVE_PRACTICE", "de"),
        ("https://www.bafin.de/DE/service/rss/_function/RSS_Massnahmen.xml", "GENERAL_DECISION", "de"),
        ("https://www.bafin.de/DE/service/rss/_function/rssnewsfeed.xml", "OTHER", "de"),
    ],
    "eba": [
        ("https://www.eba.europa.eu/rss.xml", "OTHER", "en"),
    ],
    "esma": [
        ("https://www.esma.europa.eu/rss.xml", "OTHER", "en"),
    ],
    "ecb_ssm": [
        ("https://www.bankingsupervision.europa.eu/rss/press.xml", "SUPERVISORY_STATEMENT", "en"),
    ],
    "srb": [
        ("https://www.srb.europa.eu/en/rss", "OTHER", "en"),
    ],
    "bundesbank": [
        # Nur Rundschreiben (Meldewesen); der Pressefeed (633286) besteht
        # überwiegend aus Tender-Ankündigungen und ist für das
        # High-Level-Monitoring Rauschen.
        ("https://www.bundesbank.de/service/rss/de/633302/feed.rss", "CIRCULAR", "de"),
    ],
    "bsi": [
        ("https://www.bsi.bund.de/SiteGlobals/Functions/RSSFeed/RSSNewsfeed/RSSNewsfeed_Presse_Veranstaltungen.xml", "OTHER", "de"),
    ],
    "edpb": [
        ("https://www.edpb.europa.eu/feed/news_en", "OTHER", "en"),
    ],
    "bfdi": [
        ("https://www.bfdi.bund.de/SiteGlobals/Functions/RSSFeed/Allgemein/rssnewsfeed.xml", "OTHER", "de"),
    ],
    "fiu": [
        ("https://www.zoll.de/SiteGlobals/Functions/RSSFeed/DE/RSSNewsfeed/RSSFachmeldungenFIU.xml", "OTHER", "de"),
    ],
    "esrb": [
        ("https://www.esrb.europa.eu/rss/press.xml", "OTHER", "en"),
    ],
    "fsb": [
        ("https://www.fsb.org/feed/", "OTHER", "en"),
    ],
    "cssf": [
        ("https://www.cssf.lu/en/feed/publications?content_type=circular-cssf", "CIRCULAR", "en"),
        ("https://www.cssf.lu/en/feed/publications?content_type=cssf-regulation", "REGULATION", "en"),
        ("https://www.cssf.lu/en/feed/publications?content_type=communique", "OTHER", "en"),
        ("https://www.cssf.lu/en/feed/publications?content_type=public-consultation", "CONSULTATION", "en"),
        ("https://www.cssf.lu/en/feed/publications?content_type=cssf-faq", "Q_AND_A", "en"),
        ("https://www.cssf.lu/en/feed/publications?content_type=law", "LAW", "en"),
        ("https://www.cssf.lu/en/feed/publications?content_type=grand-ducal-regulation", "LAW", "en"),
    ],
    "ecb": [
        ("https://www.ecb.europa.eu/rss/press.xml", "OTHER", "en"),
    ],
}

# Quellen, deren Detailseiten nicht gefetcht werden (nur Feed-Metadaten):
# zoll.de verlangt per robots.txt Crawl-Delay 180 s – der Feed ist zum
# Abonnieren gedacht, Seitenabrufe wären unhöflich.
RSS_NO_FETCH = {"fiu"}

# Kernnormen-Watchlist für Gesetze im Internet (Slug im URL-Pfad der TOC).
GII_WATCHLIST = {
    "kredwg": "Kreditwesengesetz (KWG)",
    "gwg_2017": "Geldwäschegesetz (GwG)",
    "wphg": "Wertpapierhandelsgesetz (WpHG)",
    "kagb": "Kapitalanlagegesetzbuch (KAGB)",
    "zag_2018": "Zahlungsdiensteaufsichtsgesetz (ZAG)",
    "vag_2016": "Versicherungsaufsichtsgesetz (VAG)",
    "pfandbg": "Pfandbriefgesetz (PfandBG)",
    "findag": "Finanzdienstleistungsaufsichtsgesetz (FinDAG)",
    "hinschg": "Hinweisgeberschutzgesetz (HinSchG)",
    "wpig": "Wertpapierinstitutsgesetz (WpIG)",
    "ewpg": "Gesetz über elektronische Wertpapiere (eWpG)",
    "sag": "Sanierungs- und Abwicklungsgesetz (SAG)",
    "einsig": "Einlagensicherungsgesetz (EinSiG)",
    "institutsvergv_2014": "Institutsvergütungsverordnung (InstitutsVergV)",
    "wpivergv": "Wertpapierinstituts-Vergütungsverordnung (WpI-VergV)",
    "ksttg": "Kryptowerte-Steuertransparenzgesetz (KStTG)",
    "sanktdg": "Sanktionsdurchsetzungsgesetz (SanktDG)",
    "awg_2013": "Außenwirtschaftsgesetz (AWG)",
    "zkg": "Zahlungskontengesetz (ZKG)",
    "lksg": "Lieferkettensorgfaltspflichtengesetz (LkSG)",
    # Ergänzt am 03.09.2026 (Gap-Analyse): NPL-Zweitmarkt, MiCA-Begleitgesetz,
    # Vermögensanlagen/Crowdfunding, Wohnimmobilienkredit, Prospektrecht.
    "krzwmg": "Kreditzweitmarktgesetz (KrZwMG)",
    "kmag": "Kryptomärkteaufsichtsgesetz (KMAG)",
    "vermanlg": "Vermögensanlagengesetz (VermAnlG)",
    "immokwplv": "Immobiliar-Kreditwürdigkeitsprüfungsleitlinien-Verordnung (ImmoKWPLV)",
    "wppg": "Wertpapierprospektgesetz (WpPG)",
}
